name: build-docker-image

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: login docker hub
        run: docker login -u ${{ secrets.docker_user_name }} -p ${{ secrets.docker_password }} 
      - uses: actions/checkout@v1
      - name: build tars demo docker
        run: |
            docker build -f Dockerfile -t tarscloud/tarsdemo:latest .
            docker push tarscloud/tarsdemo:latest